export const product = {
  image: "unsplash.png",
  title: "4 BHK House",
  address: "Golfutar, Kathmandu",
  by: "Sheetal Property",
  discription:
    "Close to Ringroad, Central location, Surrounded by friendly neighbourhood",
  facilitie: "Water Storage, Private Terrace, Parking, Garden",
  bedroom: "4",
  bathroom: "4",
  balcony: "2",
  price: "Rs. 10 Cr.",
  superArea: "2025 sq.ft",
  carpetArea: "2000 sq.ft",
  status: "Ready to move",
  floor: "2 floors",
  parking: "Available",
  landmarks: "Golfutar Basketball Court",
  overlooking: "Garden/Park, Main Road",
  facing: "Marble",
  flooring: "Marble",
  waterAvailability: "24/7 Available",
  electricity: "No/Rare Power cut",
  lift: "No",
  TotalUnits: 408,
  RoadSide: "13 to 30 ft",
  RoadType: "Gravel",
  TotalTower: 204,
  PerAana: "37 lakhs",
  PropertyType: "View Tower",
  LaunchDate: "Jan 5, 2022",
  construction: "5-10 years",
  furnishing: "Furnished",
  ownership: "Freeholder",
  report: "Sold Outs",
  Pincode: 12335,
  unitsAvailable: "1",
  PropertyStatus: "Investment",
};
